// <auto-generated />
namespace bys.activity.dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrankforactivitytype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrankforactivitytype));
        
        string IMigrationMetadata.Id
        {
            get { return "201603301107294_add rank for activity type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
