// <auto-generated />
namespace bys.activity.dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMemberTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMemberTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201603301224580_add Member Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
